-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "discount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "tax" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "transport" DECIMAL(12,2) NOT NULL DEFAULT 0;
